### PR TITLE
fix/not_loading_without_key

### LINKED ISSUE #14: Fails to create the skills settings folder and settings.json at first run
I just added the chatgpt skill to the ovos-core skills.list and run the container.

This is what you get in the logs when you try to load it for the first time and obviously the settings.json is not there with the API key

```
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.092 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: Traceback (most recent call last):
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 728, in _startup
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.initialize()
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     super().__init__(config=config)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     raise ValueError("key must be set")
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: ValueError: key must be set
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.096 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.114 - skills - ovos_workshop.skill_launcher:_create_skill_instance:473 - WARNING - Legacy skill: key must be set
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.117 - skills - ovos_workshop.skill_launcher:_create_skill_instance:482 - WARNING - Deprecation version=0.1.0. Caller=ovos_core.skill_manager:360. This initializatio>
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.232 - skills - ovos_plugin_manager.language:create:233 - INFO - Loaded the Language Translation plugin ovos-translate-plugin-server
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.240 - skills - ovos_solver_openai_persona.engines:__init__:69 - ERROR - key not set in config
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.240 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: Traceback (most recent call last):
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 728, in _startup
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.initialize()
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     super().__init__(config=config)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     raise ValueError("key must be set")
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: ValueError: key must be set
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.243 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.261 - skills - ovos_workshop.skill_launcher:_create_skill_instance:487 - ERROR - Skill __init__ failed with key must be set
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: Traceback (most recent call last):
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 485, in _create_skill_instance
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.instance._startup(self.bus, self.skill_id)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 738, in _startup
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     raise e
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 728, in _startup
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.initialize()
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     super().__init__(config=config)
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]:     raise ValueError("key must be set")
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: ValueError: key must be set
Jan 13 12:14:39 OpenVoiceOS-840dca ovos-core[8937]: 2024-01-13 12:14:39.270 - skills - ovos_workshop.skill_launcher:_communicate_load_status:510 - ERROR - Skill skill-ovos-fallback-chatgpt.openvoiceos failed to load

```

I get that the skills fails to load because of the missing API, however because it errors out, it also soes not create the skills settings folder and does not write the settings.json

Can these type of things not be improved that on first run (which is a flag) it just creates the folder and json file with an empty API key and just more silent fails to load with a line; chatgpt skipped, please set your API key in the settings.json?

(I had to create the folder and settings.json manually)

### PR DESCRIPTION
**Pull request by JarbasAl**
closes https://github.com/OpenVoiceOS/skill-ovos-fallback-chatgpt/issues/14

### CODE REVIEW

**Comment by emphasize** [comment]
To close 14 we should additionally add `DEFAULT_SETTINGS`

```python
DEFAULT_SETTINGS = {...}

def initialize(self):
    self.settings.merge(DEFAULT_SETTINGS, new_only=True)
    self.settings.store()
    ... 
```

**Comment by JarbasAl** [comment]
> To close 14 we should additionally add `DEFAULT_SETTINGS`
> 
> ```python
> DEFAULT_SETTINGS = {...}
> 
> def initialize(self):
>     self.settings.merge(DEFAULT_SETTINGS, new_only=True)
>     self.settings.store()
>     ... 
> ```

why? there are no default settings, users need to get a key

the file gets created already with `_mycroft_first_run`

**Comment by emphasize** [comment]
thought of a more fleshy config. Nevertheless, i like the key(s) to be set as a rule of thumb, waiting for values to be filled.
(the user is blindfolded, otherwise sees that there are keys without a (proper) value)

**Comment by JarbasAl** [comment]
> thought of a more fleshy config. Nevertheless, i like the key(s) to be set as a rule of thumb, waiting for values to be filled. (the user is blindfolded, otherwise sees that there are keys without a (proper) value)

id like self.chat to continue throwing an exception if key is not set, but for sure we can make that more informative than it already is with some LOGs

let's do that in another PR and keep this one just as a bugfix

**Comment by j1nx** [comment]
Tested this, however fails with the below log snippet;

```
Jan 14 10:15:05 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:05.965 - skills - ovos_workshop.skill_launcher:load:525 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: skill-ovos-fallback-chatgpt.openvoiceos
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.102 - skills - ovos_plugin_manager.language:create:233 - INFO - Loaded the Language Translation plugin ovos-translate-plugin-server
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.110 - skills - ovos_solver_openai_persona.engines:__init__:69 - ERROR - key not set in config
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.111 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.121 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.128 - skills - ovos_workshop.skill_launcher:_create_skill_instance:473 - WARNING - Legacy skill: key must be set
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.135 - skills - ovos_workshop.skill_launcher:_create_skill_instance:482 - WARNING - Deprecation version=0.1.0. Caller=ovos_core.skill_manager:360. This initializatio>
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.258 - skills - ovos_plugin_manager.language:create:233 - INFO - Loaded the Language Translation plugin ovos-translate-plugin-server
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.265 - skills - ovos_solver_openai_persona.engines:__init__:69 - ERROR - key not set in config
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.265 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.272 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.288 - skills - ovos_workshop.skill_launcher:_create_skill_instance:487 - ERROR - Skill __init__ failed with key must be set
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 485, in _create_skill_instance
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.instance._startup(self.bus, self.skill_id)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 739, in _startup
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise e
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.297 - skills - ovos_workshop.skill_launcher:_communicate_load_status:510 - ERROR - Skill skill-ovos-fallback-chatgpt.openvoiceos failed to load
```

**Comment by JarbasAl** [comment]
> Tested this, however fails with the below log snippet;
> 
> ```
> Jan 14 10:15:05 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:05.965 - skills - ovos_workshop.skill_launcher:load:525 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: skill-ovos-fallback-chatgpt.openvoiceos
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.102 - skills - ovos_plugin_manager.language:create:233 - INFO - Loaded the Language Translation plugin ovos-translate-plugin-server
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.110 - skills - ovos_solver_openai_persona.engines:__init__:69 - ERROR - key not set in config
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.111 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.121 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.128 - skills - ovos_workshop.skill_launcher:_create_skill_instance:473 - WARNING - Legacy skill: key must be set
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.135 - skills - ovos_workshop.skill_launcher:_create_skill_instance:482 - WARNING - Deprecation version=0.1.0. Caller=ovos_core.skill_manager:360. This initializatio>
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.258 - skills - ovos_plugin_manager.language:create:233 - INFO - Loaded the Language Translation plugin ovos-translate-plugin-server
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.265 - skills - ovos_solver_openai_persona.engines:__init__:69 - ERROR - key not set in config
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.265 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Skill initialization failed
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.272 - skill-ovos-fallback-chatgpt.openvoiceos - ERROR - Failed to shutdown gui for skill-ovos-fallback-chatgpt.openvoiceos: <bound method GUIInterface.gui_set of <o>
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.288 - skills - ovos_workshop.skill_launcher:_create_skill_instance:487 - ERROR - Skill __init__ failed with key must be set
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: Traceback (most recent call last):
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 485, in _create_skill_instance
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.instance._startup(self.bus, self.skill_id)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 739, in _startup
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise e
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 729, in _startup
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.initialize()
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_fallback_chatgpt/__init__.py", line 26, in initialize
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     self.chat = OpenAIPersonaSolver(config=self.settings)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/__init__.py", line 9, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     super().__init__(config=config)
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_solver_openai_persona/engines.py", line 70, in __init__
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]:     raise ValueError("key must be set")
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: ValueError: key must be set
> Jan 14 10:15:06 OpenVoiceOS-840dca ovos-core[2595]: 2024-01-14 10:15:06.297 - skills - ovos_workshop.skill_launcher:_communicate_load_status:510 - ERROR - Skill skill-ovos-fallback-chatgpt.openvoiceos failed to load
> ```

those seem to be logs without this PR applied?

**Comment by j1nx** [comment]
> 
> those seem to be logs without this PR applied?

Will double check and report back.

**Review by j1nx — COMMENTED** [review]
Re-tested and all fine. Good to merge

**Pull request merged**
